# -*- coding: utf-8 -*-
"""hi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qYutr04LIfejNDso8dTvLZytDN7VM9Kr
"""

print('hi')

